on:
  push:
    branches: [testing_map]

env:
  BASE_PATH: /testing_map
  VITE_MAPBOXKEY : ${{ secrets.VITE_MAPBOXKEY}}
  VITE_SUPABASEANONKEY : ${{ secrets.VITE_SUPABASEANONKEY}}
  VITE_SUPABASEURL : ${{ secrets.VITE_SUPABASEURL}}
  VITE_GEOCHATTERURL: https://dev.geochatter.tv/guess/geoChatterHub
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 17.6
        uses: actions/setup-node@v2
        with:
          node-version: '17.6'

      - name: 🔨 Build Project
        run: |
          npm i
          npm run build

      - name: 📂 upload to new_map
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_IP }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: ./testing_map/
